### ISSUE TITLE
Corrupted output: number of columns of result is not a multiple of vector length

### ISSUE THREAD

**Issue by alek0991** [zhengli09/PQLseq2#1]
https://github.com/zhengli09/PQLseq2/blob/bdcbfe00d0cc6224bd903ba035fd6ec28a8944ef/R/PQLseq.R#L229

Sometimes, the following warning/error arises, leading to corrupted output:

```
Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 2)
```
A potential solution for this issue could be replacing the problematic line with something like the following:

```R
if (!is.null(res$value)) {
  res = do.call(rbind, res$value)
} else {
  res = do.call(rbind, res)
}
```

You can reproduce this behavior using the following toy example: [toy_example.RData.zip](https://github.com/zhengli09/PQLseq2/files/14629916/toy_example.RData.zip)

**Comment by zhengli09** [comment]
Thank you for pointing out this issue! It has now been fixed.

**Comment by alek0991** [comment]
Thank you!
