### ISSUE TITLE
nearPD and corr=TRUE

### ISSUE THREAD

**Issue by alek0991** [zhengli09/PQLseq2#2]
https://github.com/zhengli09/PQLseq2/blob/ba5d61de3296e5d1bf288ce5cbb8a13e79159e26/R/PQLseq.R#L106

Hi Zheng,

We discussed this in an email last year (Sent: Friday, September 22, 2023, 3:00 PM). It seems that corr=TRUE has been added back, which could lead to issues.

When K (e.g., GRM) is used as a covariance matrix rather than a correlation matrix, it's essential to omit corr=TRUE. Including it can significantly modify the matrix and cause convergence problems.

Best,
Ali

**Comment by zhengli09** [comment]
Dear Ali,

Thank you for letting me know! I think I got confused at one point and ended up referring back to the old version of PQLseq. The software now has been updated such that the relatedness matrix is not constrained to be a correlation matrix.

Best,
Zheng
